Added Restore Clone plus

diff --git a/Scripts/GLOBAL b/Scripts/GLOBAL
--- a/Scripts/GLOBAL
+++ b/Scripts/GLOBAL
@@ -2,17 +2,19 @@
 
 export PATH=$PATH:/usr/lib/hyprdots-ctl/
 
-if ! source $HOME/.config/hypr/scripts/globalcontrol.sh 2> /dev/null || [[ -z "${CloneDir// }" ]]; then
-  echo "Error: Failed to source globalcontrol.sh or Cannot find Hyprdots Directory"
-  Install_Hyprdots
-  exit 1
-fi
+handle_error() { echo "Error: $1" ; Install_Hyprdots ; exit 1 ; }
+
+! source $HOME/.config/hypr/scripts/globalcontrol.sh 2> /dev/null && handle_error "Failed to source globalcontrol.sh"
+[[ -z "${CloneDir// }" ]] && handle_error "Cannot find Hyprdots Directory"
+[ ! -f "$CloneDir/Scripts/global_fn.sh" ] && handle_error "$ConfDir/Scripts/global_fn.sh does not exist"
 
 ScrDir="$ConfDir/hypr/scripts"
 ScriptDir="$CloneDir/Scripts"
 BkpDir="$ConfDir/cfg_backups"
 cacheDir="$HOME/.cache/hyprdots"
 cacheCtl="$HOME/.cache/hyprdots-ctl"
+
+barLine() { printf '=%.0s' $(seq 1 "$(tput cols)") ; }
 
 make_dir=(
   "$ScrDir"
@@ -31,6 +33,13 @@ make_dir=(
 if [ "$(ls -A "$BkpDir")" ]; then
   last_bak=$(ls -td -- $BkpDir/* | head -n 1 )
 fi
+
+rename_backup() {
+bak=$(ls -td -- "$BkpDir"/* | head -n 1 )
+if [[ "$last_bak" != $bak ]]; then
+mv "$bak" "$bak-$1"
+fi
+}
 
 
 print_prompt() {
diff --git a/Scripts/Install_Hyprdots b/Scripts/Install_Hyprdots
--- a/Scripts/Install_Hyprdots
+++ b/Scripts/Install_Hyprdots
@@ -2,25 +2,30 @@
 
 #? One Time Set up on Terminal. 
 
-vertL="$(printf '=%.0s' $(seq 1 "$(tput cols)"))"
 
-echo -e "$(tput setaf 5)\nHyprdots-ctl Cannot find the Hyprdots Directory, Will proceed to default installation!$(tput sgr0)"
-read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed? " key ; [[ -z "$key" ]] || exit 0 
+CloneDir="$HOME/Hyprdots/Scripts"
 
 
-if [ -d "$HOME/Hyprdots" ] && cd "$HOME/Hyprdots"; then
-    echo -e "\n\nDirectory $HOME/Hyprdots already exists. Using existing directory.\n"
-    echo -e "Hyprdots-ctl will make $HOME/Hyprdots your Clone Directory By restoring the links."
+barLine="$(printf '=%.0s' $(seq 1 "$(tput cols)"))"
+
+# echo -e "$(tput setaf 5)\nHyprdots-ctl Cannot find the Hyprdots Directory, Will proceed to default installation!$(tput sgr0)"
+# read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed? " key ; [[ -z "$key" ]] || exit 0 
+
+
+
+if [ -d "$CloneDir" ] && cd "$CloneDir"; then
+    echo -e "\n\nDirectory $CloneDir already exists. Using existing directory.\n"
+    echo -e "Hyprdots-ctl will make $CloneDir your Clone Directory By restoring the links."
     read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed? " key ; [[ -z "$key" ]] || exit 0 
     echo ""
 git reset --hard HEAD > /dev/null 2>&1 && git clean -fd > /dev/null 2>&1 && git pull > /dev/null 2>&1 || true
-    cd $HOME/Hyprdots/Scripts || exit 0
+    cd $CloneDir/Scripts || exit 0
     ./restore_lnk.sh
 
 else clear
 cat << GREET
 
-$vertL
+$barLine
 
 $(tput setaf 2)Hello $USER! This is an automated installation for Hyprdots.$(tput sgr0)
 
@@ -42,16 +47,16 @@ $(tput setaf 6)And wait, there's more!!! Checkout 'Hyprdots man' to see how you 
 HAVE A GOOD DAY!
 
 Visit: https://github.com/kRHYME7/Hyprdots-ctl for more information.
-$vertL
+$barLine
 GREET
 
 read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed? " key ; [[ -z "$key" ]] || exit 0 
 
  sudo /usr/lib/hyprdots-ctl/Install_ChaoticAUR --install fresh 
 
-rm -fr "$HOME/Hyprdots" || true
-git clone --depth 1 https://github.com/prasanthrangan/hyprdots $HOME/Hyprdots
-cd $HOME/Hyprdots/Scripts || exit 0
+rm -fr "$CloneDir" || true
+git clone --depth 1 https://github.com/prasanthrangan/hyprdots $CloneDir
+cd $CloneDir/Scripts || exit 0
 echo ./install.sh
 fi
 
