Format

diff --git a/Scripts/Install_ChaoticAUR b/Scripts/Install_ChaoticAUR
--- a/Scripts/Install_ChaoticAUR
+++ b/Scripts/Install_ChaoticAUR
@@ -2,22 +2,22 @@
 
 #! REQURED ROOT
 execName="$0 $*"
-rootOpts=("--install" "--purge" "--revert" "--fresh") #? List Of Flags that needs to be in sudo
+rootOpts=("--install" "--purge" "--revert" "fresh") #? List Of Flags that needs to be in sudo
 vertL="$(printf '=%.0s' $(seq 1 "$(tput cols)"))"
 
 distro_ID() { #? I'll reuse in the future.
-  local input=$(echo "$1" | tr -d ' ' | tr '[:upper:]' '[:lower:]')
-  local target=$(cat /etc/*release | grep -oP '^ID=\K[^"]+' | tr -d ' ' | tr '[:upper:]' '[:lower:]')
-  [[ "$input" == *"$target"* ]]
+    local input=$(echo "$1" | tr -d ' ' | tr '[:upper:]' '[:lower:]')
+    local target=$(cat /etc/*release | grep -oP '^ID=\K[^"]+' | tr -d ' ' | tr '[:upper:]' '[:lower:]')
+    [[ "$input" == *"$target"* ]]
 }
 
 box_me() {
-  local s="Hyprdots: $*"
-  tput setaf 3
-  echo " ═${s//?/═}"
-  echo "║$s ║"
-  echo " ═${s//?/═}"
-  tput sgr0
+    local s="Hyprdots: $*"
+    tput setaf 3
+    echo " ═${s//?/═}"
+    echo "║$s ║"
+    echo " ═${s//?/═}"
+    tput sgr0
 }
 
 check_Root() {
@@ -28,15 +28,15 @@ check_Root() {
 }
 
 check_Ping() {
-  if ! ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
-    box_me "Error: No internet connection."
-    exit 1
-  fi
+    if ! ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
+        box_me "Error: No internet connection."
+        exit 1
+    fi
 }
 
 write_ChaticAUR() {
     is_ChaoticAUR=$(grep "chaotic-aur" /etc/pacman.conf > /dev/null 2>&1 ; echo $?)
-
+    
     if [ "$1" == "append" ]; then
         box_me  "Appending Chaotic AUR"
         if [ "$is_ChaoticAUR" -eq 0 ]; then
@@ -45,7 +45,7 @@ write_ChaticAUR() {
             echo "Appending Chaotic-AUR in pacman.conf..."
             echo -e "\r\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf
         fi
-    elif [ "$1" == "remove" ]; then
+        elif [ "$1" == "remove" ]; then
         box_me "Removing Chaotic AUR from pacman.conf"
         if grep -q 'chaotic-aur' /etc/pacman.conf; then
             box_me  "Removing Chaotic AUR"
@@ -59,119 +59,119 @@ write_ChaticAUR() {
 }
 
 check_Integrity() {
-  is_ChaoticAUR=$(grep "chaotic-aur" /etc/pacman.conf > /dev/null 2>&1 ; echo $?)
-
-  if [ "$is_ChaoticAUR" -ne 0 ]; then
-    echo "Chaotic AUR entry not found in pacman.conf"
-    return 1
-  fi
-
-  if ! pacman-key -l | grep 3056513887B78AEB >/dev/null; then
-    echo "Chaotic AUR key not found"
-    return 1
-  fi
-
-  if ! pacman -Qq chaotic-keyring 2>/dev/null; then
-    echo "Chaotic AUR keyring not found"
-    return 1
-  fi
-
-  if ! pacman -Qq chaotic-mirrorlist 2>/dev/null; then
-    echo "Chaotic AUR mirrorlist not found"
-    return 1
-  fi
-
-  return 0
+    is_ChaoticAUR=$(grep "chaotic-aur" /etc/pacman.conf > /dev/null 2>&1 ; echo $?)
+    
+    if [ "$is_ChaoticAUR" -ne 0 ]; then
+        echo "Chaotic AUR entry not found in pacman.conf"
+        return 1
+    fi
+    
+    if ! pacman-key -l | grep 3056513887B78AEB >/dev/null; then
+        echo "Chaotic AUR key not found"
+        return 1
+    fi
+    
+    if ! pacman -Qq chaotic-keyring 2>/dev/null; then
+        echo "Chaotic AUR keyring not found"
+        return 1
+    fi
+    
+    if ! pacman -Qq chaotic-mirrorlist 2>/dev/null; then
+        echo "Chaotic AUR mirrorlist not found"
+        return 1
+    fi
+    
+    return 0
 }
 
-install() { 
-box_me  "Installing the key"
-pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com 
-pacman-key --lsign-key 3056513887B78AEB 
-
-box_me  "Downloading the keyring"
-pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 
-
-box_me  "Downloading the mirrorlist"
-pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' 
-
-write_ChaticAUR "append"
-
-box_me  "Refreshing the mirrorlists"
-pacman -Sy 
-
-box_me  "Chaotic-AUR has been successfully installed!"
+install() {
+    box_me  "Installing the key"
+    pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
+    pacman-key --lsign-key 3056513887B78AEB
+    
+    box_me  "Downloading the keyring"
+    pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
+    
+    box_me  "Downloading the mirrorlist"
+    pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
+    
+    write_ChaticAUR "append"
+    
+    box_me  "Refreshing the mirrorlists"
+    pacman -Sy
+    
+    box_me  "Chaotic-AUR has been successfully installed!"
 }
- 
 
-purge() { 
-  if pacman-key -l | grep 3056513887B78AEB >/dev/null; then
-    box_me  "Deleting the key"
-    pacman-key --delete EF925EA60F33D0CB85C44AD13056513887B78AEB
-  fi
 
-  if pacman -Qq chaotic-keyring 2>/dev/null; then
-    box_me  "Uninstalling the keyring"
-    pacman -Rns --noconfirm chaotic-keyring
-  fi
-
-  if pacman -Qq chaotic-mirrorlist 2>/dev/null; then
-    box_me  "Uninstalling the mirrorlist"
-    pacman -Rns --noconfirm chaotic-mirrorlist
-  fi
-
-  write_ChaticAUR "remove"
-
-  box_me  "Refreshing the mirrorlists"
-  pacman -Sy 
-
-  box_me  "Chaotic-AUR has been successfully purged"
+purge() {
+    if pacman-key -l | grep 3056513887B78AEB >/dev/null; then
+        box_me  "Deleting the key"
+        pacman-key --delete EF925EA60F33D0CB85C44AD13056513887B78AEB
+    fi
+    
+    if pacman -Qq chaotic-keyring 2>/dev/null; then
+        box_me  "Uninstalling the keyring"
+        pacman -Rns --noconfirm chaotic-keyring
+    fi
+    
+    if pacman -Qq chaotic-mirrorlist 2>/dev/null; then
+        box_me  "Uninstalling the mirrorlist"
+        pacman -Rns --noconfirm chaotic-mirrorlist
+    fi
+    
+    write_ChaticAUR "remove"
+    
+    box_me  "Refreshing the mirrorlists"
+    pacman -Sy
+    
+    box_me  "Chaotic-AUR has been successfully purged"
 }
 
 revertAUR() {
-  to_be_Reverted_AUR="$(pacman -Qmq | grep chaotic-aur)"
-
-box_me "Revert Chaotic AUR to AUR Packages"
-
-  if [[ -z "${to_be_Reverted_AUR// }" ]]; then
-    echo "No chaotic-aur package detected"
-    echo "You are Good to go!"
-    exit 0
-  fi
-
-  echo -e "Do you wish to reinstall your old Chaotic-AUR packages from AUR?\nThe following packages will be affected:\n$to_be_Reverted_AUR"
-  echo -n "Proceed? [Y/n] "
-  read ans
-
-  if [ "$ans" == "n" ] || [ "$ans" == "N" ]; then
-    box_me "Aborting..."
-    exit 0
-  fi
-
-  for chaoticPackage in $to_be_Reverted_AUR; do
-    convertedPackage="$(echo "$chaoticPackage" | sed 's/chaotic-aur/aur/')"
-
-    if [ "$(pacman -Qs "$convertedPackage")" == "$convertedPackage" ]; then
-      box_me "Reinstalling $convertedPackage..."
-      pacman -S --noconfirm "$convertedPackage"
-    else
-      box_me "Could not find $convertedPackage in the AUR."
+    to_be_Reverted_AUR="$(pacman -Qmq | grep chaotic-aur)"
+    
+    box_me "Revert Chaotic AUR to AUR Packages"
+    
+    if [[ -z "${to_be_Reverted_AUR// }" ]]; then
+        echo "No chaotic-aur package detected"
+        echo "You are Good to go!"
+        exit 0
     fi
-  done
-
-box_me "Your Chaotic-AUR packages have been reinstalled!"
-exit 0
+    
+    echo -e "Do you wish to reinstall your old Chaotic-AUR packages from AUR?\nThe following packages will be affected:\n$to_be_Reverted_AUR"
+    echo -n "Proceed? [Y/n] "
+    read ans
+    
+    if [ "$ans" == "n" ] || [ "$ans" == "N" ]; then
+        box_me "Aborting..."
+        exit 0
+    fi
+    
+    for chaoticPackage in $to_be_Reverted_AUR; do
+        convertedPackage="$(echo "$chaoticPackage" | sed 's/chaotic-aur/aur/')"
+        
+        if [ "$(pacman -Qs "$convertedPackage")" == "$convertedPackage" ]; then
+            box_me "Reinstalling $convertedPackage..."
+            pacman -S --noconfirm "$convertedPackage"
+        else
+            box_me "Could not find $convertedPackage in the AUR."
+        fi
+    done
+    
+    box_me "Your Chaotic-AUR packages have been reinstalled!"
+    exit 0
 }
 
 
 fresh() {
-clear 
-if distro_ID "Arch Linux"; then
-echo "Detected: Arch Linux"
+    clear
+    if distro_ID "Arch Linux"; then
+        echo "Detected: Arch Linux"
 cat << CHAOS
 
 $(tput setaf 2)Would you like to add Chaotic AUR to your mirror list?$(tput sgr0)
-Chaotic AUR provides prebuilt and precompiled packages, 
+Chaotic AUR provides prebuilt and precompiled packages,
 which can make installing packages from Arch faster.
 
 $vertL
@@ -191,44 +191,46 @@ $vertL
 Hyprdots-ctl is not affiliated with Chaotic AUR.
 
 CHAOS
-
-  read -p "Type 'yes' to continue [default] No : " add_chaotic
-  if [ ! "${add_chaotic}" == "yes" ]; then 
-  echo -e "$(tput setaf 1) Skipping Chaotic AUR$(tput sgr0)"
-  exit 0
-  fi
-fi
+        
+        read -p "Type 'yes' to continue [default] No : " add_chaotic
+        if [ ! "${add_chaotic}" == "yes" ]; then
+            echo -e "$(tput setaf 1) Skipping Chaotic AUR$(tput sgr0)"
+            exit 0
+        fi
+    fi
 }
 
 for option in "${rootOpts[@]}"; do if [ "$1" == "$option" ]; then  check_Ping ; check_Root
-break
-fi
+        break
+    fi
 done
 
 case "$1" in
---install)
-  if [ "$2" == "fresh" ]; then fresh ; fi
-  if check_Integrity > /dev/null; then
-    echo "Chaotic AUR already installed. Would you like a reinstall? [y/N]"
-    read ans
-    if [ "$ans" != "Y" ] && [ "$ans" != "y" ]; then echo "Chaotic AUR: Operation Cancelled."
-      exit 0
-    fi
-  fi
-  install
-  ;;
-  --purge)
-    purge
-    revertAUR
+    --install)
+        if [ "$2" == "fresh" ]; then fresh ; fi
+        if check_Integrity > /dev/null; then
+            echo "Chaotic AUR already installed. Would you like a reinstall? [y/N]"
+            read ans
+            if [ "$ans" != "Y" ] && [ "$ans" != "y" ]; then echo "Chaotic AUR: Operation Cancelled."
+                exit 0
+            fi
+        fi
+        install
     ;;
-  --revert)
-    revertAUR
+    --purge)
+        purge
+        revertAUR
     ;;
-  *)
-    echo "Invalid option: $1"
-    echo "Usage: $0 [options]
-    --install [fresh] 
-    --purge
-    --revert"
+    --revert)
+        revertAUR
+    ;;
+    *)
+  cat << HELP
+Invalid option: $1
+Usage: $0 [option]
+    --install [fresh]  ﯦ Install chaotic AUR ('fresh' assumes a fresh install)
+    --uninstall        ﯦ Uninstall chaotic AUR ( requires you to run $0 --revert after)
+    --revert           ﯦ Reinstall orphaned chaotic AUR packages
+HELP
     ;;
 esac
diff --git a/Scripts/Install_Hyde-PACMAN b/Scripts/Install_Hyde-PACMAN
--- a/Scripts/Install_Hyde-PACMAN
+++ b/Scripts/Install_Hyde-PACMAN
@@ -1,13 +1,15 @@
-#!/bin/env bash
+#! /bin/env bash
 
-#TODO: Clean This
+libDir=/usr/lib/hyde-cli
+# export PATH="$libDir:$PATH"
 
-CloneDir=${1}
-GIT=${2}
+readonly CloneDir=${1}
+export GIT=${2}
 
-barLine="$(printf '=%.0s' $(seq 1 "$(tput cols)"))"
-clear
-cat << GREET
+if [ "${fresh}" = true ]; then
+    
+    clear
+    cat <<GREET
 WOW an Arch BTW User!
 ${barLine}
 
@@ -21,7 +23,7 @@ Hyde-cli is an active helper for Hyde. During this installation, the script will
 
 From here on 'Dots' 'Dot Files' means Configurations.
 
-$(tput setaf 3)Hyde-cli is a CLI for Hyde.This aims to add patches 
+$(tput setaf 3)Hyde-cli is a CLI for Hyde.This aims to add patches
 for Hyde and address common Dots issues.
 Also this is a USER specific helper, includes a control file for a user to preserve the USER preferences.
 Please note that using these scripts may alter your Dot files.$(tput sgr0)
@@ -37,54 +39,141 @@ Clone Directory: ${CloneDir}
 Git Repository: ${GIT}
 
 GREET
+    
+    ask_confirm
+    git clone --depth 1 "${GIT}" "${CloneDir}"
+    
+    sudo ${libDir}/Install_ChaoticAUR --install fresh
+fi
 
-
-read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed?" key ; echo ; [[ -z "$key" ]] || exit 0 
-
-#? Attempt to install using Chaotic AUR
- sudo /usr/lib/hyde-cli/Install_ChaoticAUR --install fresh 
-
-# rm -fr "${CloneDir}" || true
-git clone --depth 1 "${GIT}" "${CloneDir}"
 cd "${CloneDir}"/Scripts || exit 0
+set_branch
+integrity_check "${CloneDir}"
 
-#? Select Branch
-Git_Repo=${GIT}
-    if echo "$Git_Repo" | grep -q "/tree/"; then
-        branch=${Git_Repo#*tree/} Git_Repo=${Git_Repo%/tree/*}
-    else branches=$(curl -s "https://api.github.com/repos/${Git_Repo#*://*/}/branches" | jq -r '.[].name') ; branches=($branches)
-        if [[ ${#branches[@]} -le 1 ]]; then
-            branch=${branches[0]}
-        else echo "Select a Branch"
-            select branch in "${branches[@]}"; do [[ -n $branch ]] && break || echo "Invalid selection. Please try again." ; done
-        fi
-    fi
-
-echo "Clone Directory exist: ${CloneDir}"
+echo "Clone Directory: ${CloneDir}"
 echo "Git URL: $(git remote get-url origin)"
 echo "Git Branch: ${branch}"
 
-# Change Branch
-git fetch --depth=1
- git_branch=$(git branch -a | fzf --prompt='Choose a branch')
- if [[ $git_branch == *"*"* ]]; then
-     echo "Already in branch: ${git_branch}"
- else
-# Extract the branch name without the remote prefix and trim leading whitespace
-branch_name=$(echo "${git_branch}" | sed 's/.*\///' | sed 's/^[[:space:]]*//')
-# Switch to the selected branch
-git checkout "${branch_name}"
-echo "On branch: ${branch_name}"
- fi
-
-
 custom_apps="${CloneDir}/Scripts/custom_apps.lst"
 
-if [[ -e ${custom_apps} ]] ; then 
-sed 's/^#//' "${custom_apps}" | fzf --multi --prompt='Optional packages: press [ TAB ] to select. [ ESC ] exit. [ RETURN ] confirm' > /tmp/hyde-cli-$(id -u)-temporary-apps
-echo -e "Optional packages loaded:"
-cat /tmp/hyde-cli-$(id -u)-temporary-apps
+if [[ -e ${custom_apps} ]]; then
+    sed 's/^#//' "${custom_apps}" | fzf --multi --prompt='Optional packages: press [ TAB ] to select. [ ESC ] exit. [ RETURN ] confirm' >"${install_packages_list}"
+    echo -e "Optional packages loaded:"
+    cat "${install_packages_list}"
 fi
- 
 
- ./install.sh /tmp/hyde-cli-$(id -u)-temporary-apps
+export config_override="/tmp/Hyde-${UID}-BAKmanage_cfg.lst"
+export ctlFile="${ctlDir}/manage_cfg.lstl"
+[ -e $ctlFile ] && cp $ctlFile $config_override
+[ ! -e $ctlFile ] && Manage_Configs restore_Lister "OVERWRITE"
+Manage_Configs list_Marker "${CloneDir}" --custom
+ask_confirm "${USER}"
+# trap 'rm -f ./install_pkg.lst' EXIT
+#  ./install.sh "${install_packages_list}"
+
+#--------------------------------#
+# import variables and functions #
+#--------------------------------#
+scrDir="${CloneDir}/Scripts"
+source "${scrDir}/global_fn.sh" || true
+if [ $? -ne 0 ]; then
+    echo "Error: unable to source global_fn.sh..."
+    exit 1
+fi
+"${scrDir}/install_pre.sh"
+
+#----------------------#
+# prepare package list #
+#----------------------#
+shift $((OPTIND - 1))
+cust_pkg=$1
+cp "${scrDir}/custom_hypr.lst" "${install_packages_list}"
+
+if [ -f "${cust_pkg}" ] && [ ! -z "${cust_pkg}" ]; then
+    cat "${cust_pkg}" >>"${install_packages_list}"
+fi
+
+#--------------------------------#
+# add nvidia drivers to the list #
+#--------------------------------#
+if nvidia_detect; then
+    cat /usr/lib/modules/*/pkgbase | while read krnl; do
+        echo "${krnl}-headers" >>"${install_packages_list}"
+    done
+    IFS=$' ' read -r -d '' -a nvga < <(lspci -k | grep -E "(VGA|3D)" | grep -i nvidia | awk -F ':' '{print $NF}' | tr -d '[]()' && printf '\0')
+    for nvcode in "${nvga[@]}"; do
+        awk -F '|' -v nvc="${nvcode}" '{if ($3 == nvc) {split(FILENAME,driver,"/"); print driver[length(driver)],"\nnvidia-utils"}}' "${scrDir}"/.nvidia/nvidia*dkms >>"${install_packages_list}"
+    done
+fi
+
+echo -e "\033[0;32m[GPU]\033[0m detected // $dGPU"
+
+#----------------#
+# get user prefs #
+#----------------#
+if ! chk_list "aurhlpr" "${aurList[@]}"; then
+    echo -e "Available aur helpers:\n[1] yay\n[2] paru"
+    prompt_timer 120 "Enter option number"
+    
+    case "${promptIn}" in
+        1) export getAur="yay" ;;
+        2) export getAur="paru" ;;
+        *)
+            echo -e "...Invalid option selected..."
+            exit 1
+        ;;
+    esac
+fi
+
+if ! chk_list "myShell" "${shlList[@]}"; then
+    echo -e "Select shell:\n[1] zsh\n[2] fish"
+    prompt_timer 120 "Enter option number"
+    
+    case "${promptIn}" in
+        1) export myShell="zsh" ;;
+        2) export myShell="fish" ;;
+        *)
+            echo -e "...Invalid option selected..."
+            exit 1
+        ;;
+    esac
+    echo "${myShell}" >>"${install_packages_list}"
+fi
+
+#--------------------------------#
+# install packages from the list #
+#--------------------------------#
+#? "${scrDir}/install_pkg.sh" "${install_packages_list}"
+#? rm "${install_packages_list}"
+
+#---------------------------#
+# restore my custom configs #
+#---------------------------#
+
+# "${scrDir}/restore_fnt.sh"
+# "${scrDir}/restore_cfg.sh"
+# cat ./restore_cfg.lst
+./restore_fnt.sh
+Restore_Config --only "/tmp/Hyde-$(id -u)-BAK" ${CloneDir}/Configs
+
+#---------------------#
+# post-install script #
+#---------------------#
+
+"${scrDir}/install_pst.sh"
+
+#------------------------#
+# enable system services #
+#------------------------#
+
+while read servChk; do
+    
+    if [[ $(systemctl list-units --all -t service --full --no-legend "${servChk}.service" | sed 's/^\s*//g' | cut -f1 -d' ') == "${servChk}.service" ]]; then
+        echo -e "\033[0;33m[SKIP]\033[0m ${servChk} service is active..."
+    else
+        echo -e "\033[0;32m[systemctl]\033[0m starting ${servChk} system service..."
+        sudo systemctl enable "${servChk}.service"
+        sudo systemctl start "${servChk}.service"
+    fi
+    
+done <"${scrDir}/system_ctl.lst"
diff --git a/Scripts/Install_Hyprdots b/Scripts/Install_Hyprdots
--- a/Scripts/Install_Hyprdots
+++ b/Scripts/Install_Hyprdots
@@ -1,71 +1,71 @@
 #!/bin/env bash
 
 is_link=false
-    while (( "$#" )); do
-        case "$1" in
-            --CLONE)
-                CloneDir="$2"
-                shift  2
-                ;;
-            --LINK)
-                 CloneDir=${2}
-                 is_link=true
-                shift  2
-                ;;
-            --GIT)
-                GIT="$2"
-                shift  2
-                ;;
-            *)
-                echo "Unknown option: $1"
-                exit  1
-                ;;
-        esac
-    done
+while (( "$#" )); do
+    case "$1" in
+        --CLONE)
+            CloneDir="$2"
+            shift  2
+        ;;
+        --LINK)
+            CloneDir=${2}
+            is_link=true
+            shift  2
+        ;;
+        --GIT)
+            GIT="$2"
+            shift  2
+        ;;
+        *)
+            echo "Unknown option: $1"
+            exit  1
+        ;;
+    esac
+done
 [[ -n ${CloneDir} ]] && echo "Set Clone Directory: ${CloneDir}"
 [[ ${is_link} == true ]] && echo "Linked to Clone Directory: ${CloneDir}"
 [[ -n ${GIT} ]] &&    echo "Cloning from: ${GIT}"
 
-    # Set default values if not provided
-    CloneDir=${CloneDir:-${HOME}/Hyprdots}
-    GIT=${GIT:-"https://github.com/prasanthrangan/hyprdots"}
+# Set default values if not provided
+CloneDir=${CloneDir:-${HOME}/Hyprdots}
+GIT=${GIT:-"https://github.com/prasanthrangan/hyprdots"}
 
 
-#? One Time Set up on Terminal. 
+#? One Time Set up on Terminal.
 install_distro() {
-
-  # echo -e "$(tput setaf 5)\nHyprdots-ctl Cannot find the Hyprdots Directory, Will proceed to default installation!$(tput sgr0)"
-  # read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed? " key ; [[ -z "$key" ]] || exit 0 
-  distro_ID=$(cat /etc/*release | grep -oP '^ID=\K[^"]+' | tr -d ' ' | tr '[:upper:]' '[:lower:]')
-
-case "${distro_ID}" in
-  "fedora")
-    echo "This is Fedora"
-     Install_Hyprdots-DNF "${CloneDir}" "${GIT}"
-    ;;
-  "arch")
-     Install_Hyprdots-PACMAN "${CloneDir}" "${GIT}"
-    ;;
-  *)
-    echo "This is neither Fedora nor Arch"
-    # Add the commands for other distributions here
-    ;;
-esac
+    
+    # echo -e "$(tput setaf 5)\nHyprdots-ctl Cannot find the Hyprdots Directory, Will proceed to default installation!$(tput sgr0)"
+    # read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed? " key ; [[ -z "$key" ]] || exit 0
+    distro_ID=$(cat /etc/*release | grep -oP '^ID=\K[^"]+' | tr -d ' ' | tr '[:upper:]' '[:lower:]')
+    
+    case "${distro_ID}" in
+        "fedora")
+            echo "This is Fedora"
+            Install_Hyprdots-DNF "${CloneDir}" "${GIT}"
+        ;;
+        "arch")
+            Install_Hyprdots-PACMAN "${CloneDir}" "${GIT}"
+        ;;
+        *)
+            echo "This is neither Fedora nor Arch"
+            # Add the commands for other distributions here
+        ;;
+    esac
 }
 
 export PATH=${PATH}:/usr/lib/hyprdots-ctl/
 
-if [[ -d "${CloneDir}" ]] && cd "${CloneDir}"; then 
-  cd "${CloneDir}"/Scripts || exit 0
-  echo -e "\nDirectory exist: ${CloneDir}\n[*]Using existing directory.\n[*]Changes will be stashed\n"
-  read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed?" key ; [[ -z "${key}" ]] || exit 0 
-  git reset --hard HEAD  && git clean -fd  && git pull  || true
-      if [[ ${is_link} == true ]]; then
-          echo -e "Hyprdots-ctl will make ${CloneDir} your Clone Directory By restoring the links."
-          ./restore_lnk.sh
-      else
-      install_distro
-      fi
-else 
-install_distro
+if [[ -d "${CloneDir}" ]] && cd "${CloneDir}"; then
+    cd "${CloneDir}"/Scripts || exit 0
+    echo -e "\nDirectory exist: ${CloneDir}\n[*]Using existing directory.\n[*]Changes will be stashed\n"
+    read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed?" key ; [[ -z "${key}" ]] || exit 0
+    git reset --hard HEAD  && git clean -fd  && git pull  || true
+    if [[ ${is_link} == true ]]; then
+        echo -e "Hyprdots-ctl will make ${CloneDir} your Clone Directory By restoring the links."
+        ./restore_lnk.sh
+    else
+        install_distro
+    fi
+else
+    install_distro
 fi
